booking_system/booking/urls.py
from django.urls import path

from . import views

app_name = 'booking'

urlpatterns = [
    path('', views.index, name='index'),
    path('location/<int:pk>/', views.location_detail, name='location_detail'),
    path('location/<int:pk>/book', views.create_booking, name='create_booking'),
    path('activate/<uuid:code>/', views.activate_booking, name='activation'),
    path('like/<int:location_id>/', views.like_location, name='like_location'),
    path('dislike/<int:location_id>/', views.dislike_location, name='dislike_location'),
    path(
        'favourite/<int:location_id>/',
        views.favourite_location,
        name='favourite_location',
    ),
    path('review/<int:review_id>/delete/', views.delete_review, name='delete_review'),
]

booking_system/booking_system/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('admin/', admin.site.urls),
    path('', include('booking.urls')),
    path('accounts/', include('accounts.urls')),
]

booking_system/booking/forms.py
from typing import Any, Dict

from django import forms
from django.core.exceptions import ValidationError
from django.utils.timezone import now

from .models import Booking, Review


class BookingForm(forms.ModelForm):
    """Форма для бронювання локації."""

    start_time = forms.DateTimeField(
        required=True,
        initial=now,
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        label='Дата початку',
    )
    end_time = forms.DateTimeField(
        required=True,
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        label='Дата закінчення',
    )

    def clean(self) -> Dict[str, Any]:
        """
        Перевіряє чи дата початку бронювання не пізніше дати закінчення.

        Returns:
            Dict[str, Any]: Очищені дані форми.
        """
        cleaned_data = super().clean()
        start_time = cleaned_data.get('start_time')
        end_time = cleaned_data.get('end_time')

        if start_time and end_time:
            if start_time >= end_time:
                raise ValidationError('Дата закінчення має бути пізніше дати початку.')

            if start_time < now():
                raise ValidationError('Дата початку не може бути в минулому.')

        return cleaned_data

    class Meta:
        """Метаклас форми, який визначає метадані форми."""

        model = Booking
        exclude = ['user', 'location', 'confirmed']


class ReviewForm(forms.ModelForm):
    """Форма для відгуку."""

    rating = forms.IntegerField(label='Рейтинг', min_value=1, max_value=5)
    comment = forms.CharField(widget=forms.Textarea, label='Коментар')

    class Meta:
        """Метаклас форми, який визначає метадані форми."""

        model = Review
        fields = ['rating', 'comment']

booking_system/booking/views.py
from datetime import datetime

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.db.models import F
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.timezone import make_aware, now

from .forms import BookingForm, ReviewForm
from .models import Booking, Favourite, Location, Reaction, Review


def index(request: HttpRequest) -> HttpResponse:
    """
    Відображає головну сторінку зі списком локацій.

    Args:
        request (HttpRequest): Запит.

    Returns:
        HttpResponse: Відповідь сервера зі списком локацій.
    """
    locations = Location.objects.all()

    # Параметри сортування та фільтрування
    sort_by = request.GET.get('sort_by', 'name')
    query = request.GET.get('q', '')
    start_date = request.GET.get('start_date')
    end_date = request.GET.get('end_date')

    # Сортування
    ordering_options = {
        'name': 'name',
        'price': 'price_per_night',
        'rating': '-rating',
    }
    if sort_by in ordering_options:
        locations = locations.order_by(ordering_options[sort_by])

    # Фільтрування за пошуковим запитом
    if query:
        locations = locations.filter(name__icontains=query)

    # Фільтрування за датами
    if start_date and end_date:
        start_dt = make_aware(datetime.strptime(start_date, '%Y-%m-%d'))
        end_dt = make_aware(datetime.strptime(end_date, '%Y-%m-%d'))
        booked_location_ids = Booking.objects.filter(
            confirmed=True, start_time__lt=end_dt, end_time__gt=start_dt
        ).values_list('location_id', flat=True)
        locations = locations.exclude(id__in=booked_location_ids)

    # Улюблені локації
    favourites = (
        Location.objects.filter(favourites__user=request.user)
        if request.user.is_authenticated
        else None
    )

    booked_location_ids = Booking.objects.filter(
        start_time__lte=now(), end_time__gte=now()
    ).values_list('location_id', flat=True)

    return render(
        request,
        'index.html',
        context={
            'locations': locations,
            'sort_by': sort_by,
            'booked_location_ids': booked_location_ids,
            'query': query,
            'start_date': start_date,
            'end_date': end_date,
            'favourites': favourites,
        },
    )


def location_detail(request: HttpRequest, pk: int) -> HttpResponse:
    """
    Відображає деталі локації та список відгуків.

    Args:
        request (HttpRequest): Запит.
        pk (int): Ідентифікатор локації.

    Returns:
        HttpResponse: Відповідь сервера з деталями локації.
    """
    location = get_object_or_404(Location, pk=pk)
    reviews = location.reviews.all()
    user_review = (
        Review.objects.filter(user=request.user, location=location).first()
        if request.user.is_authenticated
        else None
    )

    # Улюблені локації
    favourites = (
        Location.objects.filter(favourites__user=request.user)
        if request.user.is_authenticated
        else None
    )

    if request.method == 'POST' and not user_review:
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            review.location = location
            review.save()
            return redirect('booking:location_detail', pk=pk)
    else:
        review_form = ReviewForm()

    return render(
        request,
        'location_detail.html',
        context={
            'location': location,
            'reviews': reviews,
            'review_form': review_form,
            'user_review': user_review,
            'favourites': favourites,
        },
    )


def send_activation_email(request: HttpRequest, booking: Booking) -> None:
    subject = f'Підтведіть бронювання: {booking.location.name}'
    base_url = f'{request.scheme}://{request.get_host()}'
    activation_link = f'{base_url}/activate/{booking.activation_code}/'

    message = f"""
    <html lang="uk">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>{subject}</title>
        </head>
        <body style="font-family: Arial, sans-serif; background-color: #f4f4f4; padding: 20px; text-align: center;">
            <div style="max-width: 500px; margin: auto; background-color: #ffffff; padding: 25px; border-radius: 10px; box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);">
                <h2 style="color: #333; margin-bottom: 20px;">Підтвердження бронювання</h2>
                <p style="color: #555; line-height: 1.5;">Вітаємо, {booking.user}, дякуємо за ваше бронювання <strong>{booking.location.name}</strong>!</p>
                <p style="color: #555; line-height: 1.5;">Для його підтвердження, будь ласка, натисніть кнопку нижче:</p>
                <p style="margin: 20px 0;">
                    <a href="{activation_link}" style="display: inline-block; padding: 12px 24px; background-color: #28a745; color: #ffffff; text-decoration: none; font-size: 16px; font-weight: bold; border-radius: 5px;">Підтвердити бронювання</a>
                </p>
                <p style="color: #555; line-height: 1.5;">Ваше бронювання з <strong>{booking.start_time.strftime('%d.%m.%Y')}</strong> по <strong>{booking.end_time.strftime('%d.%m.%Y')}</strong>.</p>
                <hr style="border: none; border-top: 1px solid #ddd; margin: 20px 0;">
                <p style="font-size: 12px; color: #777; line-height: 1.5;">Якщо ви не здійснювали це бронювання - проігноруйте цей лист.</p>
            </div>
        </body>
    </html>
    """

    send_mail(
        subject,
        '',
        settings.EMAIL_HOST_USER,
        [booking.user.email],
        html_message=message,
    )


@login_required
def activate_booking(request: HttpRequest, code: int) -> HttpResponse:
    """
    Активує бронювання за кодом активації.

    Args:
        request (HttpRequest): Запит.
        code (int): Код активації.

    Returns:
        HttpResponse: Відповідь сервера.
    """
    booking = get_object_or_404(Booking, activation_code=code)
    booking.confirmed = True
    booking.save()

    return render(request, 'activation_page.html', {'booking': booking.id})


@login_required
def create_booking(request: HttpRequest, pk: int) -> HttpResponse:
    """
    Створює бронювання для локації.

    Args:
        request (HttpRequest): Запит.
        pk (int): Ідентифікатор локації.

    Returns:
        HttpResponse: Відповідь сервера з формою бронювання.
    """
    location = get_object_or_404(Location, pk=pk)
    form = BookingForm(request.POST or None, initial={'start_time': now()})

    if request.method == 'POST' and form.is_valid():
        booking = form.save(commit=False)
        booking.user = request.user
        booking.location = location
        booking.confirmed = False

        if Booking.objects.filter(
            location=location,
            confirmed=True,
            start_time__lt=booking.end_time,
            end_time__gt=booking.start_time,
        ).exists():
            form.add_error(
                None, 'Цей час уже зайнятий. Будь ласка, оберіть інший період.'
            )
        else:
            send_activation_email(request, booking)
            booking.save()
            return redirect('booking:index')

    return render(request, 'booking_form.html', {'form': form, 'location': location})


@login_required
def delete_review(request: HttpRequest, review_id: int) -> HttpResponse:
    """
    Видаляє відгук користувача.

    Args:
        request (HttpRequest): Запит.
        review_id (int): Ідентифікатор відгуку.

    Returns:
        HttpResponse: Відповідь сервера.
    """
    review = get_object_or_404(Review, pk=review_id)

    if review.user == request.user or request.user.is_staff:
        location_id = review.location.id
        review.delete()
        review.location.update_rating()
        return redirect('booking:location_detail', pk=location_id)

    return HttpResponse(status=403)


@login_required
def like_location(request: HttpRequest, location_id: int) -> HttpResponse:
    """
    Обробляє лайк користувача для локації.

    Args:
        request (HttpRequest): Запит.
        location_id (int): Ідентифікатор локації.

    Returns:
        HttpResponse: Відповідь сервера.
    """
    location = get_object_or_404(Location, pk=location_id)
    like, created = Reaction.objects.get_or_create(
        user=request.user, location=location, reaction_type='like'
    )

    if not created:  # Видаляє лайк, якщо він вже існує
        like.delete()
    else:  # Видаляє дизлайк, якщо він вже існує
        Reaction.objects.filter(
            user=request.user, location=location, reaction_type='dislike'
        ).delete()

    # Оновлює кількість лайків та дизлайків
    location.update_like_count()
    location.update_dislike_count()

    return redirect('booking:location_detail', pk=location_id)


@login_required
def dislike_location(request: HttpRequest, location_id: int) -> HttpResponse:
    """
    Обробляє дизлайк користувача для локації.

    Args:
        request (HttpRequest): Запит.
        location_id (int): Ідентифікатор локації.

    Returns:
        HttpResponse: Відповідь сервера.
    """
    location = get_object_or_404(Location, pk=location_id)
    dislike, created = Reaction.objects.get_or_create(
        user=request.user, location=location, reaction_type='dislike'
    )

    if not created:  # Видаляє дизлайк, якщо він вже існує
        dislike.delete()
    else:  # Видаляє лайк, якщо він вже існує
        Reaction.objects.filter(
            user=request.user, location=location, reaction_type='like'
        ).delete()

    # Оновлює кількість лайків та дизлайків
    location.update_like_count()

booking_system/templates/activation_page.html
{% extends 'base/_base.html' %}
{% load static %}

{% block title %}
Система бронювання
{% endblock %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/loader.css' %}">

    <!-- Підтвердження бронювання -->
    <div class="text-center" id="booking-confirmation">
        <h2 class="font-weight-bold">Ваше бронювання успішно підтверджено!</h2>
        <h6 class="font-weight-bold">Мені трохи самотньо, можливо залишишся?</h6>
        <img src="{% static 'images/cute.png' %}" alt="Логотип" class="img-fluid" style="width: 35px; height: 35px;">
        <br><br>
        <button class="btn btn-primary" id="send-button" onclick="showLoader()">Залишитися</button>
    </div>

    <!-- Анімація завантаження -->
    <div class="text-center" style="display: none;" id="loading">
        <h1>Будь ласка, зачекайте,<br>йде відправка даних до СБУ</h1>
        <div class="loader"><br></div>
        <div class="message" style="display: none;">Успішно відправлено!</div>
    </div>

    <!-- Скрипт для анімації завантаження -->
    <script src="{% static 'js/loader.js' %}"></script>
{% endblock %}

booking_system/templates/booking_form.html
{% extends 'base/_base.html' %}
{% load crispy_forms_filters %}

{% block title %}
Бронювання - {{ location.name }}
{% endblock %}

{% block content %}
<div class="container">
  <h1 class="text-center mb-4">Бронювання: {{ location.name }}</h1>

  <!-- Форма бронювання -->
  <div class="row justify-content-center">
    <div class="col-md-8">
      <form method="post" class="card p-4">
        {% csrf_token %} 
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary mt-3">Забронювати</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

booking_system/templates/index.html
{% extends 'base/_base.html' %}
{% load static %}

{% block title %}
Система бронювання
{% endblock %}

{% block content %}
<div class="container">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">

    <h1 class="my-4">Знайдіть та забронюйте потрібну вам локацію</h1>

    <!-- Пошук -->
    <form method="get" class="mb-3">
        <div class="input-group">
            <input class="form-control" type="search" placeholder="Пошук" aria-label="Пошук" name="q" value="{{ query }}">
            <button class="btn btn-outline-success" type="submit">Пошук</button>
        </div>
    </form>

    <!-- Сортування -->
    <form method="get" class="mb-3">
        <div class="input-group">
            <label class="input-group-text" for="sort_by">Сортувати за:</label>
            <select class="form-select" id="sort_by" name="sort_by" onchange="this.form.submit()">
                <option value="name" {% if sort_by == 'name' %}selected{% endif %}>Назвою</option>
                <option value="price" {% if sort_by == 'price' %}selected{% endif %}>Ціною</option>
                <option value="rating" {% if sort_by == 'rating' %}selected{% endif %}>Рейтингом</option>
            </select>
            {% if query %}
            <input type="hidden" name="q" value="{{ query }}">
            {% endif %}
        </div>
    </form>

    <!-- Фільтрування за часом -->
    <form method="get" class="mb-3">
        <div class="input-group">
            <input type="date" class="form-control" name="start_date" value="{{ request.GET.start_date }}">
            <input type="date" class="form-control" name="end_date" value="{{ request.GET.end_date }}">
            <button class="btn btn-outline-success" type="submit">Пошук</button>
        </div>
    </form>

    <!-- Улюблені локації -->
    {% for location in favourites %}
    <h2 class="my-4">Збережені локації</h2>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        <div class="col">
            <div class="card h-100">
                <img src="{{ location.photo }}" class="card-img-top" alt="{{ location.name }}" style="height: 200px; object-fit: cover;">
                <div class="card-body">
                    <h5 class="card-title">
                        <a href="{% url 'booking:location_detail' location.pk %}" class="text-decoration-none">{{ location.name }}</a>
                    </h5>
                    <p class="card-text">{{ location.city }}, {{ location.country }}</p>
                    <p class="card-text">{{ location.price_per_night }} грн / ніч</p>
                    <span class="badge {% if location.is_booked %}bg-danger{% else %}bg-success{% endif %}">{{ location.is_booked|yesno:"Станом на зараз заброньовано,Станом на зараз доступно" }}</span>
                    <div class="mt-2">
                        <a href="{% url 'booking:location_detail' location.pk %}" class="btn btn-outline-primary">Переглянути</a>
                        <a href="{% url 'booking:create_booking' location.pk %}" class="btn btn-primary">Забронювати</a>
                        {{ location.like_count }} <i class="fa-regular fa-thumbs-up"></i> {{ location.dislike_count }} <i class="fa-regular fa-thumbs-down"></i>
                        <i class="{% if location in favourites %}fa-solid{% else %}fa-regular{% endif %} fa-heart"></i>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <!-- Локації -->
    <h2 class="my-4">Усі локації</h2>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for location in locations %}
        <div class="col">
            <div class="card h-100">
                <img src="{{ location.photo }}" class="card-img-top" alt="{{ location.name }}" style="height: 200px; object-fit: cover;">
                <div class="card-body">
                    <h5 class="card-title">
                        <a href="{% url 'booking:location_detail' location.pk %}" class="text-decoration-none">{{ location.name }}</a>
                    </h5>
                    <p class="card-text">{{ location.city }}, {{ location.country }}</p>
                    <p class="card-text">{{ location.price_per_night }} грн / ніч</p>
                    <span class="badge {% if location.is_booked %}bg-danger{% else %}bg-success{% endif %}">{{ location.is_booked|yesno:"Станом на зараз заброньовано,Станом на зараз доступно" }}</span>
                    <div class="mt-2">
                        <a href="{% url 'booking:location_detail' location.pk %}" class="btn btn-outline-primary">Переглянути</a>
                        <a href="{% url 'booking:create_booking' location.pk %}" class="btn btn-primary">Забронювати</a>
                        <span>{{ location.like_count }} <i class="fa-regular fa-thumbs-up"></i></span>
                        <span>{{ location.dislike_count }} <i class="fa-regular fa-thumbs-down"></i></span>
                        {% if location in favourites %}
                        <i class="fa-solid fa-heart"></i>
                        {% else %}
                        <i class="fa-regular fa-heart"></i>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
        <p>Нічого не знайдено.</p>
        {% endfor %}
    </div>
</div>

<!-- Кнопка "Контакти" -->
<button type="button" class="btn btn-primary rounded-circle p-3 position-fixed" id="hoverButton" style="width: 60px; height: 60px; bottom: 20px; right: 20px;">
    <i class="fa-solid fa-phone-volume"></i>
</button>

<!-- Модальне вікно -->
<div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Наші контакти</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрити"></button>
            </div>
            <div class="modal-body">
                <p>📧 Написати email <code>nemo.bma@gmail.com</code></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрити</button>
            </div>
        </div>
    </div>
</div>

<!-- Скрипт для відкриття модального вікна при наведенні -->
<script src="{% static 'js/open_modal.js' %}"></script>
{% endblock %}

booking_system/templates/location_detail.html
{% extends 'base/_base.html' %}
{% load crispy_forms_filters %}

{% block title %}
Докладніше про {{ location.name }}
{% endblock %}

{% block content %}
<div class="container">
  <!-- Докладна інформація про локацію -->
  <div class="row">
    <div class="col-md-8">
      <div class="card mb-3">
        <img src="{{ location.photo }}" alt="{{ location.name }}" class="img-fluid card-img-top" style="max-height: 500px; object-fit: cover" />
        <div class="card-body">
          <h1 class="card-title">{{ location.name }}</h1>
          <p class="lead">{{ location.description }}</p>
          <p>Місцезнаходження: {{ location.city }}, {{ location.country }}</p>
          {% if location.rating != 0 %}
          <p>Рейтинг: {{ location.rating }}</p>
          {% else %}
          <p>Рейтинг: Немає</p>
          {% endif %}
          <p>Ціна за ніч: {{ location.price_per_night }} грн</p>
          <p>Місткість: {{ location.amount }}</p>

          <div class="d-flex">
            <form method="POST" action="{% url 'booking:like_location' location.pk %}" class="me-2">
              {% csrf_token %}
              <button type="submit" class="btn btn-outline-primary">👍 Лайк ({{ location.like_count }})</button>
            </form>
            <form method="POST" action="{% url 'booking:dislike_location' location.pk %}" class="me-2">
              {% csrf_token %}
              <button type="submit" class="btn btn-outline-danger">👎 Дизлайк ({{ location.dislike_count }})</button>
            </form>
            <form method="POST" action="{% url 'booking:favourite_location' location.pk %}">
              {% csrf_token %}
              {% if location in favourites %}
              <button type="submit" class="btn btn-outline-danger">❤️ Прибрати з улюблених</button>
              {% else %}
              <button type="submit" class="btn btn-outline-danger">🤍 Додати до улюблених</button>
              {% endif %}
          </form>
          </div>

          {% if request.user.is_authenticated and not user_review %}
            </br>
            <h3>Залишити відгук</h3>
            <form method="POST">
              {% csrf_token %}
              {{ review_form|crispy }}
              <button type="submit" class="btn btn-primary">Опублікувати</button>
            </form>
          {% endif %}
        </div>
      </div>
    </div>

    <!-- Кнопка "Забронювати" -->
    <div class="col-md-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Забронюйте вже зараз!</h5>
          <a href="{% url 'booking:create_booking' location.pk %}" class="btn btn-success w-100">Забронювати</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Відгуки -->
  <div class="mt-5">
    <h3>Відгуки</h3>
    {% for review in reviews %}
      <div class="card mb-3">
        <div class="card-body">
          {% if review.user.first_name and review.user.last_name %}
          <h5 class="card-title">{{ review.user.first_name }} {{ review.user.last_name }}</h5>
          {% else %}
          <h5 class="card-title">{{ review.user.username}}</h5>
          {% endif %}
          <p class="card-text">{{ review.comment }}</p>
          <p class="card-text"><small class="text-muted">Рейтинг: {{ review.rating }}</small></p>
          {% if review.user == request.user or request.user.is_staff %}
            <a href="{% url 'booking:delete_review' review.pk %}" class="btn btn-danger btn-sm">Видалити</a>
          {% endif %}
        </div>
      </div>
    {% empty %}
      <p>Немає відгуків.</p>
    {% endfor %}
  </div>

  <!-- Кнопка "Назад до списку" -->
  <a href="{% url 'booking:index' %}" class="btn btn-secondary mt-3">Назад до списку</a>
</div>
{% endblock %}